---
- name: Set IP Interface
  hosts: all

  tasks:
    - name: Set Interface IPv4 address
      ios_l3_interface:
        name: Ethernet0/{{item.interface}}
        #ipv4: 192.168.{{item.ip}}.1/24
        name: no shut
      with_items:
        - { interface: 1, ip: 1 }
        - { interface: 2, ip: 2 }
        - { interface: 3, ip: 3 }

    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
